projects/weatherapp/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'



urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
]

projects/weatherapp/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'



urlpatterns = [
    path('contact', views.contact, name="contact"),
    
]

projects/weatherapp/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'



urlpatterns = [    
    path('<int:id>', views.profile, name="profile"),
    path('add_city', views.profile_add_city, name="add_city"),
    path('del_city', views.profile_del_city, name="del_city")
]

projects/weatherapp/weatherapp/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('contact/', include('contact.urls'), name='contact'),    
    path ('profiles/', include('userprofile.urls'), name='userprofile'),
    # path ('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

projects/weatherapp/userprofile/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile_cities(models.Model):
    city = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.city

projects/weatherapp/userprofile/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.middleware.csrf import get_token
from django.contrib.auth import login, logout, user_logged_in, user_logged_out
from .models import Profile_cities as db
from django.contrib import messages
from django.contrib.auth.models import User
import requests

url = "https://api.openweathermap.org/data/2.5/weather?q={city_name}&units=imperial&appid=XXXXXXXXXXXXXXXXXXXXXXXXX"

def profile(request, id):    
    profile_cities_list = db.objects.filter(user_id=id)     
    profile_cities = [city for city in profile_cities_list]
    if profile_cities:         
        cities = get_weather(profile_cities)  
        return render(request, 'userprofile/profile.html', {'cities' : cities})
    return render(request, 'userprofile/profile.html', {'cities' : ""})

def profile_add_city (request):    
    if request.method == 'POST' and request.POST.get('city'):        
        resp_owm =  requests.get(url.format(city_name=request.POST.get('city'))).json()
        user = request.user         
        
        if resp_owm['cod'] == 200:
            city = db.objects.filter(city=request.POST.get('city'),user=user)
            if city:  
                return redirect('userprofile:profile', id=user.id)
            else:
                new_city = db(city=request.POST.get('city'),user=user)
                new_city.save()
                return redirect('userprofile:profile',  id=user.id)
        else:           
          return redirect('userprofile:profile',  id=user.id)
    return redirect('userprofile:profile',  id=user.id)
    
def profile_del_city (request):    
    if request.method == 'POST' and request.POST.get('close_city'): 
        user = request.user         
        del_city = db.objects.filter(user=user, city__icontains=request.POST.get('close_city'))         
        if del_city:            
            del_city.delete()       
        return redirect('userprofile:profile',  id=user.id)   

    return redirect('userprofile:profile',  id=user.id)


def get_weather (cities):    
    profile_ui_cities =  []
    for city in cities:        
        resp_owm =  requests.get(url.format(city_name=city.city)).json()
        city = {
        'city' : resp_owm['name'],
        'temperature' : resp_owm['main']['temp'],
        'high' : resp_owm['main']['temp_max'],
        'low' : resp_owm['main']['temp_min'],
        'description' : resp_owm['weather'][0]['description'],
        'icon' :resp_owm['weather'][0]['icon'],
        'country_flag': resp_owm['sys']['country'].lower(),
        'country': resp_owm['sys']['country']}
        profile_ui_cities.append(city)
    return profile_ui_cities     

projects/weatherapp/userprofile/templates/userprofile/profile.html
{% extends "base.html" %}

{% block nav %}  
<a class="nav-link" href="{% url 'accounts:signout' %}">Logout</a>
{% endblock nav %} 

{% block showcase %}

<div class="container-fluid">
  <div class="h5 text-center" style="width: fit-content; background: #6C7C59; color: #00308F; font-size: 2rem;font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;"> {{ user }}'s Profile</div>
  <div class="container-fluid">
    <form class="form-home" action="{% url 'userprofile:add_city' %}" method="post"> 
      {% csrf_token %}
      <input required class="form-input" type="text" name="city" placeholder="Enter your city">    
      <button type="submit" class="btn btn-dark button-profile" name="add_city">Add</button> 
    </form> 
    
  </div>
    <div class="container-fluid">
      <div class="row">
        {% for weather in cities %}
        <div class="col-3">
          <div class="card">
            <div class="card-body">
              <form method="post" action="{% url 'userprofile:del_city' %}"> 
                {% csrf_token %}              
                <button type="submit" class="btn-close btn-dark" name="close_city" value="{{ weather.city }}"></button>
              </form>
              <h5 class="card-title">{{ weather.city }}, {{weather.country}} <img src="https://openweathermap.org/images/flags/{{weather.country_flag}}.png" alt=""></h5>
              <h1 class="card-title">{{ weather.temperature }}°</h1>
              <img src="http://openweathermap.org/img/wn/{{weather.icon}}@4x.png"  alt="...">          
              <p class="lead card-text ">{{ weather.description }} </p>
              <p class="lead card-text"><span class="text-danger">H:{{ weather.high }}°
              </span><span class="text-info">L:{{ weather.low }}°</span></p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endblock showcase %}