projects/weatherapp/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'



urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
]

projects/weatherapp/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'



urlpatterns = [
    path('contact', views.contact, name="contact"),
    
]

projects/weatherapp/weatherapp/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('contact/', include('contact.urls'), name='contact'),    
    path ('profiles/', include('userprofile.urls'), name='userprofile'),
    # path ('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

projects/weatherapp/contact/models.py
from django.db import models

# Create your models here.
class ContactForm(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email

projects/weatherapp/contact/forms.py
from django.forms import ModelForm
from .models import ContactForm


class ContactForm(ModelForm):
    class Meta:
        model = ContactForm
        fields = '__all__'

projects/weatherapp/contact/views.py
from django.shortcuts import render, redirect
from django.middleware.csrf import get_token
from .forms import ContactForm

# Create your views here.
def contact(request):
    csrf_token = get_token(request)    
    form = ContactForm()    
    return render(request, 'contact/contact.html', {'form':form})

projects/weatherapp/contact/templates/contact/contact.html
{% extends "base.html" %}

{% block nav %}    
  <a class="nav-link" href="{% url 'contact:contact' %}">Contact Us</a>
  <a class="nav-link" href="{% url 'accounts:signin' %}">Sign In</a>
{% endblock nav %}  
{% block showcase %}
    <div class="container text-center">   
      <div class="container-contact bg-white ">        
        <div class="row mt-2">
          <!--card -1-->
          <div class=" col-lg-6 col-cards">
            <div class="cards">
              <div class="h1 pt-2">
                <i class="bi bi-telephone"></i>
              </div>                
              <div class="card-body">
                <h5 class="card-title">Call Us</h5>
                <h6 class="card-subtitle pt-2">Headquarters (Toll-Free)</h6> 
                <h6 class="cards-text">800.888.1000</h6>
                <h6 class="card-subtitle pt-2">Headquarters </h6>
                <h6 class="cards-text">801 801 1000</h6>
              </div>
            </div>            
        </div>
        <!--card -2-->
        <div class="col-lg-6 col-cards">
          <div class="cards">
            <div class="h1 pt-2">
              <i class="bi bi-geo-alt-fill"></i>
            </div>                
            <div class="card-body">
              <h5 class="card-title">Come See Us</h5>
              <h6 class="cards-text pt-4">WeatherInc HQ</h6> 
              <h6 class="cards-text">77 weather st</h6>
              <h6 class="cards-text">Beach Street, FL 22001 </h6>
            </div>
          </div>            
        </div>
        <div class="container-contact form-container">
          <form method="POST" action="">
            {% csrf_token %}
            <fieldset class="form-group">                               
                    {{ form }}  
            </fieldset>           
            <input type="submit" value="Contact Us">
        </form>
        </div>
    </div>
    </div>  
 {% endblock showcase %}